[phases.setup]
nixPkgs = ["tesseract", "python311", "gcc", "pkg-config"]

[phases.install]
cmds = [
    "pip install --upgrade pip",
    "pip install -r requirements.txt --no-cache-dir"
]

[phases.build]
cmds = [
    "echo 'Build phase complete'",
    "python -c 'import pytesseract; print(\"OCR test:\", pytesseract.get_tesseract_version())'"
]

[start]
cmd = "python app.py"

[variables]
NIXPACKS_INSTALL_CMD = "pip install -r requirements.txt --no-cache-dir" 